site_name: Mario Arroyo - Portfolio de Análisis y Ciencia de Datos
theme:
  name: material
  palette:
    scheme: slate # Tema oscuro profesional
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Inicio: index.md
  - Proyectos Ciencia de Datos:
      - Product Testing: proyectos_ciencia_de_datos/Product_testing/Product_testing.md
      - Evasión de Clientes: proyectos_ciencia_de_datos/Evasion_clientes/Evasion_clientes.md
      - Tech Sales: proyectos_ciencia_de_datos/Tech_sales/Tech_sales.md
  - Habilidades: habilidades.md