site_name: Mario Arroyo - Portfolio de Análisis y Ciencia de Datos
theme:
  name: material
  palette:
    scheme: slate # Tema oscuro profesional
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Data Science Projects:
      - Product Testing: proyectos_ciencia_de_datos/Product_testing/Product_testing.md
      - Customer Churn: proyectos_ciencia_de_datos/Evacion_clientes/evasion_clientes.md
  - Data Analysis Projects:
    - Human Resources: proyectos_analisis_de_datos/Recursos_humanos/Recursos_humanos.md
    - Tech Sales: proyectos_analisis_de_datos/tech_sales/tech_sales.md
